### PR TITLE
chore: add windows to CI

### PR DESCRIPTION
**Pull request by styfle**
- Related to https://github.com/vercel/webpack-asset-relocator-loader/pull/155
- Related to https://github.com/vercel/ncc/issues/593

### CODE REVIEW

**Comment by styfle** [comment]
@yichi-yang Any thoughts what could be wrong here? Looks like the tests already strip `\r` but its still showing up

https://github.com/vercel/ncc/blob/905222e371dbf7f04c3b6dc39660b9dc58da4933/test/unit.test.js#L22-L23

**Comment by yichi-yang** [comment]
> @yichi-yang Any thoughts what could be wrong here? Looks like the tests already strip `\r` but its still showing up

I'm not super familiar with the unit test setup here, but just by looking at the code my guess would be it's `actualSourceMap` that contain `\r`s?

https://github.com/vercel/ncc/blob/905222e371dbf7f04c3b6dc39660b9dc58da4933/test/unit.test.js#L81

**Comment by styfle** [comment]
That one also has a replace, so still not sure why it fails CI 🤔 

https://github.com/vercel/ncc/blob/905222e371dbf7f04c3b6dc39660b9dc58da4933/test/unit.test.js#L76-L79

**Comment by yichi-yang** [comment]
Ah I think you need `/\\r/g` instead of `/\r/g`. Those `\r`s in map appear to already have been escaped.

**Pull request merged**
