### PR TITLE
fix: upgrade to `terser@5.31.0` to fix minfy with negated `in` statements

### LINKED ISSUE #1193: Outdated Terser causes a syntax issue when minify-ing code
We are trying to swap out `node-fetch` for `undici`, but unfortunately we are running into ncc compiling issues. Specifically, there is a patched issue with Terser removing parentheses for `!(#test in this)`, causing the syntax issue.

- The issue was fixed in Terser starting from `terser@5.30.3`, see https://github.com/terser/terser/issues/1516.
- The code that triggered this issue can be found in `undici`'s code itself: https://github.com/nodejs/undici/blob/2c9bc0b74f914a120a0497efad791b471767dc55/lib/web/fetch/util.js#L882C7-L882C75

Is it possible to release a patch version with a more up-to-date Terser, to include this fix?

### PR DESCRIPTION
**Pull request by byCedric**
Fixes #1193

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Thanks for the PR! Looks like CI is failing however.

https://github.com/vercel/ncc/actions/runs/9369710285/job/25854934076?pr=1194#step:9:335

**Comment by byCedric** [comment]
These are interesting failures, I'm not sure why Node 20 on Ubuntu causes that error, while Node 20 on Windows seems fine.

The MacOS errors are just `node-gyp` (install) related issues, likely due to the GHA runner missing some low-level dependency.

**Comment by byCedric** [comment]
Also interesting here is that the last run on workflow (4 months ago) did not succeed for Node 20 on Ubuntu ([this run](https://github.com/vercel/ncc/actions/runs/7873890228)). Unfortunately, the logs have been wiped already, but that might be a pointer to this failure too.

I'm also guessing the `macos-latest` runner has been changed within 4 months, causing the CI failures.

**Comment by styfle** [comment]
I see what you mean. I'll run CI against main to see how it compares:

https://github.com/vercel/ncc/pull/1195

**Comment by byCedric** [comment]
Glad we you could repro this on `main` (as in, not caused by this PR) 😄

Anything I can do to help?

**Comment by styfle** [comment]
I think we need to fix main before merging this to confirm it works as expected

**Comment by theoludwig** [comment]
> I think we need to fix main before merging this to confirm it works as expected

What was the problem with CI (the logs disappeared)? Should probably run CI again, with all the depdencies updated to their latest version, to see the status of the project.

**Comment by styfle** [comment]
@theoludwig Feel free to create a new PR to fix it

**Comment by theoludwig** [comment]
> @theoludwig Feel free to create a new PR to fix it

Alright. :smile: https://github.com/vercel/ncc/pull/1213

Tests are working locally, but about CI, I don't know, need an approval to run it. Hopefully, it fixes the issue, and allow to update terser and webpack to latest version to get latest fixes like this one with negated `in` statements.

**Pull request closed without merging**
